variable vpc_cidr_block {}
variable subnet_cidr_block {}
variable avail_zone {}
variable env_prefix {}
variable "my_ip" {}
variable "instance_type" {}
variable "key_pair" {}
variable "public_kay_location" {}
variable "docker_script" {}
variable "image_name" {}
